#!/usr/bin/env bash
# Render production .env for EC2 docker-compose.prod.yml
# Required vars are injected from GitHub Actions secrets.
# Everything else falls back to current prod defaults.
set -euo pipefail

require_var() {
  local name="$1"
  local value="${!name:-}"
  if [ -z "$value" ]; then
    echo "Missing required variable: $name" >&2
    exit 1
  fi
}

require_var DATABASE_URL
require_var JWT_SECRET
require_var LINE_BOT_CHANNEL_ACCESS_TOKEN
require_var LINE_BOT_CHANNEL_SECRET

# Optional overrides (GitHub secret / variable). Empty = use prod default below.
FRONTEND_URL="${FRONTEND_URL:-https://crm-web.vortex-dev.com}"
CORS_ORIGINS="${CORS_ORIGINS:-https://main.d2t43thpr4t9mh.amplifyapp.com}"
LIFF_ENDPOINT_URL="${LIFF_ENDPOINT_URL:-https://crm-web.vortex-dev.com/liff/login}"
MINIO_PUBLIC_URL="${MINIO_PUBLIC_URL:-http://13.229.89.126:9000}"
RABBITMQ_USER="${RABBITMQ_USER:-crm}"
RABBITMQ_PASS="${RABBITMQ_PASS:-changeme}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-minioadmin}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-minioadmin}"

cat <<EOF
# Generated by CI/CD — do not edit manually (will be overwritten on deploy)
DEPLOY_TAG=${DEPLOY_TAG:-unknown}
DEPLOY_SHA=${DEPLOY_SHA:-unknown}
DEPLOYED_AT=${DEPLOYED_AT:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}

NODE_ENV=production
PORT=3000
API_PREFIX=api/v1
LOG_LEVEL=info

DATABASE_URL=${DATABASE_URL}

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=7d

LINE_BOT_CHANNEL_ACCESS_TOKEN=${LINE_BOT_CHANNEL_ACCESS_TOKEN}
LINE_BOT_CHANNEL_SECRET=${LINE_BOT_CHANNEL_SECRET}

OTP_CODE=123456
OTP_TTL_SECONDS=60

FRONTEND_URL=${FRONTEND_URL}
CORS_ORIGINS=${CORS_ORIGINS}
LIFF_ENDPOINT_URL=${LIFF_ENDPOINT_URL}

AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
RABBITMQ_USER=${RABBITMQ_USER}
RABBITMQ_PASS=${RABBITMQ_PASS}

MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_BUCKET=crm-lineoa
MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}

API_HOST_PORT=3000
MINIO_HOST_PORT=9000
EOF
